// The 20 Tier-2 town pages (Watauga County + High Country). Rendered by
// src/pages/tree-service-[town].astro at /tree-service-{slug}.
//
// Each town's full page is built by makeTown() from a compact config so every
// page carries the town name through its H1, intro copy, FAQ, nearby links, and
// map — without 20× hand-written duplication. Town-specific character comes from
// the `character`, `nearby`, and `note` fields. All towns are inside the GBP
// service area (Watauga County core); we mention "and surrounding areas" in body
// copy only, and do NOT build pages for out-of-footprint towns (Banner Elk,
// Beech Mountain, Newland, West Jefferson, Fleetwood, or any VA town).

export interface Town {
  slug: string; // route param → /tree-service-{slug}
  name: string;
  state: string;
  county: string;
  title: string;
  metaDescription: string;
  h1: string;
  heroTag: string;
  heroSub: string;
  heroTrust: string[];
  stats: { number: string; label: string }[];
  body: { tag: string; html: string }[];
  faq: { q: string; a: string }[];
  nearby: { label: string; href: string }[];
  reviewsTitle: string;
  reviewsSub: string;
  faqTitle: string;
  faqSub: string;
  areaTitle: string;
  areaSub: string;
  areaInfoHeading: string;
  areaInfoBlurb: string;
  finalCta: string;
  contactHeading: string;
  contactDesc: string;
}

interface TownConfig {
  slug: string;
  name: string;
  state?: string;
  /** One clause describing the place — woven into the intro. */
  character: string;
  /** Slugs of nearby towns for internal links (labels resolved from the set). */
  nearby: string[];
  /** Optional extra local line for the intro. */
  note?: string;
}

const PHONE = "(828) 964-6567";

// The town configs. `character` is a short descriptive clause; `nearby` links to
// neighbors. Everything else is generated by makeTown().
const townConfigs: TownConfig[] = [
  { slug: "deep-gap-nc", name: "Deep Gap", character: "our home base, tucked along the Blue Ridge east of Boone", nearby: ["boone-nc", "todd-nc", "triplett-nc", "bamboo-nc", "stony-fork-nc"], note: "Deep Gap is where River Birch is based, so you're getting a truly local crew — not one driving up the mountain from out of the area." },
  { slug: "boone-nc", name: "Boone", character: "the heart of the High Country and home to Appalachian State", nearby: ["deep-gap-nc", "blowing-rock-nc", "bamboo-nc", "sands-nc", "meat-camp-nc"], note: "From tight university-town lots to wooded ridgetop homes, Boone has every kind of tree job — and we handle all of them." },
  { slug: "blowing-rock-nc", name: "Blowing Rock", character: "the scenic village on the edge of the escarpment", nearby: ["boone-nc", "foscoe-nc", "aho-nc", "deep-gap-nc"], note: "Many Blowing Rock properties are prized for their long-range views, so selective view clearing is one of our most-requested jobs here." },
  { slug: "vilas-nc", name: "Vilas", character: "the rural community west of Boone along Highway 421", nearby: ["sugar-grove-nc", "zionville-nc", "cove-creek-nc", "boone-nc"] },
  { slug: "sugar-grove-nc", name: "Sugar Grove", character: "the Cove Creek–area community in western Watauga County", nearby: ["vilas-nc", "valle-crucis-nc", "cove-creek-nc", "boone-nc"] },
  { slug: "valle-crucis-nc", name: "Valle Crucis", character: "the historic valley community along the Watauga River", nearby: ["sugar-grove-nc", "foscoe-nc", "vilas-nc", "boone-nc"] },
  { slug: "foscoe-nc", name: "Foscoe", character: "the community stretched along Highway 105 between Boone and Linville", nearby: ["valle-crucis-nc", "seven-devils-nc", "blowing-rock-nc", "boone-nc"] },
  { slug: "seven-devils-nc", name: "Seven Devils", character: "the high mountain town straddling the Watauga–Avery line", nearby: ["foscoe-nc", "blowing-rock-nc", "boone-nc"], note: "At elevation, Seven Devils takes some of the heaviest ice and wind in the area — which is exactly when our 24/7 storm response matters most." },
  { slug: "zionville-nc", name: "Zionville", character: "the community near the Tennessee line in northwestern Watauga County", nearby: ["mabel-nc", "trade-nc", "vilas-nc", "cove-creek-nc"] },
  { slug: "trade-nc", name: "Trade", state: "TN", character: "the historic community just over the line, the oldest unincorporated town in Tennessee", nearby: ["zionville-nc", "mabel-nc", "vilas-nc"], note: "We cover Trade and the NC/TN line communities right alongside our Watauga County service area." },
  { slug: "mabel-nc", name: "Mabel", character: "the rural community in the northwestern corner of the county", nearby: ["zionville-nc", "cove-creek-nc", "vilas-nc"] },
  { slug: "cove-creek-nc", name: "Cove Creek", character: "the western Watauga community around the Cove Creek schools", nearby: ["sugar-grove-nc", "vilas-nc", "mabel-nc", "zionville-nc"] },
  { slug: "meat-camp-nc", name: "Meat Camp", character: "the community in the hills north of Boone", nearby: ["boone-nc", "sands-nc", "todd-nc", "deep-gap-nc"] },
  { slug: "sands-nc", name: "Sands", character: "the community just north of Boone", nearby: ["boone-nc", "meat-camp-nc", "deep-gap-nc"] },
  { slug: "bamboo-nc", name: "Bamboo", character: "the community between Boone and Blowing Rock", nearby: ["boone-nc", "blowing-rock-nc", "deep-gap-nc"] },
  { slug: "aho-nc", name: "Aho", character: "the community in the hills near Blowing Rock", nearby: ["blowing-rock-nc", "foscoe-nc", "boone-nc"] },
  { slug: "triplett-nc", name: "Triplett", character: "the community in eastern Watauga County near the Wilkes line", nearby: ["deep-gap-nc", "todd-nc", "stony-fork-nc"] },
  { slug: "todd-nc", name: "Todd", character: "the riverside community on the Watauga–Ashe line along the New River", nearby: ["deep-gap-nc", "meat-camp-nc", "triplett-nc"] },
  { slug: "brownwood-nc", name: "Brownwood", character: "the community in eastern Watauga County", nearby: ["deep-gap-nc", "stony-fork-nc", "triplett-nc"] },
  { slug: "stony-fork-nc", name: "Stony Fork", character: "the community along the eastern edge of the county toward Deep Gap", nearby: ["deep-gap-nc", "triplett-nc", "brownwood-nc"] },
];

const nameBySlug: Record<string, string> = Object.fromEntries(
  townConfigs.map((t) => [t.slug, t.name]),
);

function makeTown(cfg: TownConfig): Town {
  const { slug, name } = cfg;
  const state = cfg.state ?? "NC";
  const county = "Watauga County";
  const nearby = cfg.nearby
    .filter((s) => nameBySlug[s])
    .map((s) => ({ label: `${nameBySlug[s]}, ${townConfigs.find((t) => t.slug === s)?.state ?? "NC"}`, href: `/tree-service-${s}` }));
  const nearbyProse = cfg.nearby.map((s) => nameBySlug[s]).filter(Boolean).slice(0, 3).join(", ");

  return {
    slug,
    name,
    state,
    county,
    title: `Tree Service in ${name}, ${state} | Tree Removal & Storm Cleanup | River Birch`,
    metaDescription: `Fully-insured tree removal, 24/7 storm & ice cleanup, trimming, stump grinding & land clearing in ${name}, ${state}. Local River Birch crew, 5.0★ on Google. Free estimates — ${PHONE}.`,
    h1: `Tree Service in ${name}, ${state}`,
    heroTag: "🌲 Local, Fully-Insured & 24/7",
    heroSub: `River Birch Tree Service brings safe, insured tree removal, storm & ice cleanup, trimming, stump grinding, and land clearing to ${name} and the surrounding High Country. Owner Ezequiel Moreno and crew are based right here in ${county}.`,
    heroTrust: ["5.0★ on Google", "Fully Insured", "24/7 Emergency", "Free Estimates"],
    stats: [
      { number: "24/7", label: "Emergency Response" },
      { number: "5.0★", label: "Rated on Google" },
      { number: "Insured", label: "On Every Job" },
      { number: "Free", label: "On-Site Estimates" },
    ],
    body: [
      { tag: "h2", html: `Your Local Tree Service in ${name}` },
      { tag: "p", html: `River Birch Tree Service is a locally owned, fully-insured tree company serving ${name} — ${cfg.character} — and the rest of ${county}. We handle everything from a single hazardous removal to full land clearing, and we answer the phone 24/7 when a storm brings a tree down. ${cfg.note ?? ""}` },
      { tag: "p", html: `Owner Ezequiel Moreno and the River Birch crew have earned a 5.0-star reputation on Google across the High Country by showing up on time, working safely near homes and power lines, and leaving every ${name} property cleaner than we found it.` },
      { tag: "h2", html: `Tree Services We Offer in ${name}` },
      { tag: "li", html: `<a href="/tree-removal">Tree removal</a>, including technical removals near homes and power lines` },
      { tag: "li", html: `<a href="/storm-damage-tree-removal">24/7 emergency storm & ice-damage cleanup</a>` },
      { tag: "li", html: `<a href="/land-clearing">Land, lot & driveway clearing</a> for building and reclaiming property` },
      { tag: "li", html: `<a href="/tree-trimming-pruning">Tree trimming & pruning</a> to keep your trees healthy and safe` },
      { tag: "li", html: `<a href="/stump-grinding">Stump grinding</a> below grade, with cleanup` },
      { tag: "li", html: `<a href="/view-clearing">View clearing</a> to reclaim your long-range mountain views` },
      { tag: "h2", html: `Why ${name} Homeowners Choose River Birch` },
      { tag: "p", html: `The High Country throws a lot at your trees — heavy ice, high winds, steep and rocky lots, and long stretches of forest right against the house. Working ${name} properties safely takes local know-how and the right insurance, and we bring both. We're close by in Deep Gap, so we reach ${name} and nearby ${nearbyProse} quickly, and we travel for larger jobs beyond ${county} too. Call River Birch at ${PHONE} for a free estimate.` },
    ],
    faq: [
      { q: `Does River Birch serve ${name}?`, a: `Yes — ${name} is right in our service area. River Birch is based in nearby Deep Gap and covers all of ${county} and the surrounding High Country. Call ${PHONE} for a free estimate.` },
      { q: `Can you remove a tree near my house or power line in ${name}?`, a: `Absolutely. Technical removals near homes and power lines are a specialty. We climb and rope the tree down in controlled pieces so nothing hits the structure — and River Birch is fully insured for exactly this kind of work in ${name}.` },
      { q: `Do you offer emergency tree service in ${name} after storms?`, a: `Yes. When ice or wind brings a tree down in ${name}, River Birch answers 24/7. We make the scene safe, clear the tree off your home or driveway, and haul off the debris — any hour, any day.` },
      { q: `Is River Birch insured?`, a: `Yes. River Birch Tree Service LLC is fully insured for tree work in ${name} and throughout ${county}. North Carolina has no state arborist license, so insurance is what actually protects your property — and we carry it on every job.` },
      { q: `Are estimates free in ${name}?`, a: `Always. We come out to your ${name} property, look at the job, and give you a clear, written, no-pressure estimate. Call ${PHONE} to set one up.` },
    ],
    nearby,
    reviewsTitle: `What ${name}-Area Homeowners Say`,
    reviewsSub: "Real 5-star Google reviews from around the High Country.",
    faqTitle: `Tree Service in ${name} — Common Questions`,
    faqSub: `Quick answers for ${name} homeowners about removal, storms, insurance, and estimates.`,
    areaTitle: `River Birch Serves ${name} & All of ${county}`,
    areaSub: `Based in Deep Gap, we cover ${name} and the surrounding High Country. Explore nearby towns below.`,
    areaInfoHeading: `Covering ${name} & Nearby`,
    areaInfoBlurb: `We reach ${name} and neighboring ${nearbyProse} quickly from our Deep Gap base — and travel for large jobs beyond the county line.`,
    finalCta: `Need a Tree Handled in ${name}? Let's Talk.`,
    contactHeading: `Get a Free Estimate in ${name}`,
    contactDesc: `Tell us about your tree or project in ${name}, or call us — we'll come out and give you a clear, no-pressure price. For a tree that's down right now, call anytime; we're on 24/7.`,
  };
}

export const locations: Record<string, Town> = Object.fromEntries(
  townConfigs.map((cfg) => [cfg.slug, makeTown(cfg)]),
);
